import { ExternalLink, GraduationCap, BriefcaseBusiness, Sparkles, Landmark, ShieldCheck, ArrowRight, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Layout } from '@/components/layout/Layout'
import { SEOHead } from '@/components/common/SEOHead'

const opportunities = [
  { title: 'Federal Government Scholarship Board', type: 'Scholarships', audience: 'Undergraduate and postgraduate students', description: 'The Federal Ministry of Education scholarship platform for local and international scholarship opportunities.', url: 'https://scholarship.education.gov.ng/', icon: GraduationCap, tone: 'bg-[#e7efe7] text-[#2f5b48]' },
  { title: 'PTDF Scholarship Portal', type: 'Scholarships', audience: 'Students in oil, gas, and energy-related fields', description: 'Official Petroleum Technology Development Fund scholarship management portal and application guidance.', url: 'https://scholarship.ptdf.gov.ng/', icon: GraduationCap, tone: 'bg-[#f4eadc] text-[#9b5b2d]' },
  { title: 'NELFUND Student Loan', type: 'Student funding', audience: 'Eligible Nigerian tertiary students', description: 'Apply for the official interest-free student loan and check your application status through the NELFUND portal.', url: 'https://portal.nelf.gov.ng/', icon: Landmark, tone: 'bg-[#e8e8f2] text-[#4b4a82]' },
  { title: 'Federal Civil Service Vacancies', type: 'Employment', audience: 'Qualified Nigerian professionals', description: 'Check open vacancies and official recruitment notices from the Federal Civil Service Commission.', url: 'https://recruitment.fedcivilservice.gov.ng/', icon: BriefcaseBusiness, tone: 'bg-[#f2e8e8] text-[#8b3f3f]' },
  { title: 'Digital Training Academy', type: 'Skills', audience: 'Young people and professionals', description: 'Free digital and professional skills training supported by the Federal Government of Nigeria.', url: 'https://dta.education.gov.ng/', icon: Sparkles, tone: 'bg-[#e4edf3] text-[#27627b]' },
  { title: 'Ekiti Scholarship & Bursary Board', type: 'Ekiti opportunities', audience: 'Indigenes and students of Ekiti State', description: 'Official Ekiti scholarship and bursary application information for eligible students.', url: 'https://scholarshipessb.com/', icon: GraduationCap, tone: 'bg-[#efe9dc] text-[#765a29]' },
]

export default function Opportunities() {
  return <Layout><SEOHead title="Opportunities Desk – MyTownpedia" description="A trusted desk for scholarships, student funding, jobs, skills training and public opportunities for Ekiti residents and Nigerians." type="website" />
    <main className="bg-[#f7f3ec] text-[#1e2926]">
      <section className="border-b border-[#1e2926]/15 bg-[#304943] text-[#f7f3ec]"><div className="mx-auto max-w-7xl px-5 py-16 md:px-10 md:py-24"><div className="max-w-3xl"><p className="mb-4 text-xs font-bold uppercase tracking-[0.22em] text-[#e4b27b]">MyTownpedia Opportunity Desk</p><h1 className="font-serif text-5xl font-bold leading-[0.95] tracking-[-0.04em] md:text-7xl">Find the door.<br /><span className="text-[#e4b27b]">Know the deadline.</span></h1><p className="mt-7 max-w-2xl font-serif text-xl leading-relaxed text-[#f7f3ec]/75">A focused, verified starting point for scholarships, student funding, employment, skills training and public opportunities that can change a life.</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-bold uppercase tracking-[0.14em]"><span className="border border-white/25 px-4 py-2">Federal sources</span><span className="border border-white/25 px-4 py-2">Ekiti sources</span><span className="border border-white/25 px-4 py-2">No payment required to browse</span></div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-12 md:px-10"><div className="mb-10 flex flex-col justify-between gap-5 border-b border-[#1e2926]/20 pb-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b36b3b]">Start here</p><h2 className="mt-2 font-serif text-4xl font-bold">Verified opportunity sources</h2></div><p className="max-w-md font-serif text-base leading-relaxed text-[#68736d]">We link you to the official application page. Always confirm eligibility, opening dates and deadlines on the source website before applying.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{opportunities.map((item) => { const Icon = item.icon; return <article key={item.title} className="flex flex-col border border-[#1e2926]/15 bg-white/45 p-6 transition hover:-translate-y-1 hover:border-[#b36b3b]/60 hover:shadow-lg"><div className="flex items-start justify-between"><div className={`flex h-12 w-12 items-center justify-center rounded-full ${item.tone}`}><Icon className="h-6 w-6" /></div><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#68736d]">{item.type}</span></div><h3 className="mt-6 font-serif text-2xl font-bold leading-tight">{item.title}</h3><p className="mt-3 text-xs font-bold uppercase tracking-[0.12em] text-[#b36b3b]">{item.audience}</p><p className="mt-3 flex-1 font-serif leading-relaxed text-[#68736d]">{item.description}</p><a href={item.url} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 border-t border-[#1e2926]/15 pt-4 text-xs font-bold uppercase tracking-[0.14em] text-[#1e2926] hover:text-[#b36b3b]">Open official source <ExternalLink className="h-4 w-4 text-[#b36b3b]" /></a></article> })}</div></section>
      <section className="border-y border-[#1e2926]/15 bg-[#e9dfcf]"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-10 md:flex-row md:items-center md:justify-between md:px-10"><div className="flex gap-4"><ShieldCheck className="mt-1 h-7 w-7 shrink-0 text-[#2f5b48]" /><div><h2 className="font-serif text-2xl font-bold">Safety first</h2><p className="mt-2 max-w-2xl leading-relaxed text-[#68736d]">MyTownpedia does not collect application fees or ask for your password. We point you to official destinations and flag suspicious claims. Never pay an individual for access to a government opportunity.</p></div></div><Link to="/news" className="inline-flex shrink-0 items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-[#2f5b48]">Read verified updates <ArrowRight className="h-4 w-4" /></Link></div></section>
      <section className="mx-auto max-w-7xl px-5 py-14 text-center md:px-10"><Search className="mx-auto h-8 w-8 text-[#b36b3b]" /><h2 className="mt-4 font-serif text-3xl font-bold">Looking for a specific opportunity?</h2><p className="mx-auto mt-3 max-w-xl font-serif text-lg text-[#68736d]">Follow the Newsroom for new openings, deadline reminders, local notices and application guidance as they are verified.</p><Link to="/news" className="mt-6 inline-flex items-center gap-2 bg-[#b36b3b] px-6 py-3 text-xs font-bold uppercase tracking-[0.15em] text-white hover:bg-[#934f2a]">Go to the Newsroom <ArrowRight className="h-4 w-4" /></Link></section>
    </main>
  </Layout>
}
