import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Calendar, Eye, Share2, Facebook, Twitter, Linkedin, Loader2, ShieldCheck } from 'lucide-react';
import { useAuth } from '@/hooks/useAuth';
import { Helmet } from 'react-helmet-async';
interface NewsArticle { id: string; title: string; content: string; excerpt: string; cover_image_url: string | null; category: string; tags: string[]; published_at: string; view_count: number; }
export default function NewsDetail() {
  const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const { user } = useAuth();
  const [article, setArticle] = useState<NewsArticle | null>(null); const [loading, setLoading] = useState(true); const [copied, setCopied] = useState(false);
  useEffect(() => { if (id) fetchArticle(); }, [id]);
  const fetchArticle = async () => { try { setLoading(true); const { data, error } = await supabase.from('news').select('*').eq('id', id).single(); if (error) throw error; if (data) { setArticle({ ...data, tags: Array.isArray(data.tags) ? data.tags : [] }); await supabase.from('news').update({ view_count: (data.view_count || 0) + 1 }).eq('id', id); } } catch (error) { console.error('Error fetching article:', error); } finally { setLoading(false); } };
  const formatDate = (date: string) => new Date(date).toLocaleDateString('en-NG', { day: '2-digit', month: 'long', year: 'numeric' });
  const wordCount = article?.content?.trim().split(/\s+/).length || 0; const readTime = Math.max(1, Math.ceil(wordCount / 220)); const shareUrl = typeof window !== 'undefined' ? window.location.href : ''; const shareTitle = article?.title || 'MyTownpedia News';
  const handleShare = (platform: 'copy' | 'facebook' | 'twitter' | 'linkedin') => { const url = encodeURIComponent(shareUrl); const title = encodeURIComponent(shareTitle); if (platform === 'copy') { navigator.clipboard.writeText(shareUrl); setCopied(true); setTimeout(() => setCopied(false), 2000); } if (platform === 'facebook') window.open(`https://www.facebook.com/sharer/sharer.php?u=${url}`, '_blank'); if (platform === 'twitter') window.open(`https://twitter.com/intent/tweet?text=${title}&url=${url}`, '_blank'); if (platform === 'linkedin') window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}`, '_blank'); };
  if (loading) return <div className="flex min-h-screen items-center justify-center bg-[#f7f3ec]"><Loader2 className="h-8 w-8 animate-spin text-[#b36b3b]" /></div>;
  if (!article) return <div className="flex min-h-screen items-center justify-center bg-[#f7f3ec]"><div className="text-center"><h2 className="font-serif text-3xl font-bold">Article not found</h2><Button asChild className="mt-5"><Link to="/news">Back to Newsroom</Link></Button></div></div>;
  return <><Helmet><title>{article.title} | MyTownpedia Newsroom</title><meta name="description" content={article.excerpt || article.content.substring(0, 160)} /><meta property="og:title" content={article.title} /><meta property="og:description" content={article.excerpt || article.content.substring(0, 160)} />{article.cover_image_url && <meta property="og:image" content={article.cover_image_url} />}</Helmet>
    <main className="min-h-screen bg-[#f7f3ec] text-[#1e2926]"><div className="mx-auto max-w-5xl px-5 py-7 md:px-10"><Link to="/news" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-[#68736d] hover:text-[#b36b3b]"><ArrowLeft className="h-4 w-4" /> Back to newsroom</Link><div className="mt-12 border-b border-[#1e2926]/20 pb-10"><div className="mb-5 flex flex-wrap items-center gap-3 text-xs font-bold uppercase tracking-[0.16em] text-[#b36b3b]"><span>{article.category || 'Community'}</span><span className="text-[#68736d]">{formatDate(article.published_at)}</span><span className="text-[#68736d]">{readTime} min read</span></div><h1 className="max-w-4xl font-serif text-4xl font-bold leading-[1.05] tracking-[-0.03em] md:text-7xl">{article.title}</h1>{article.excerpt && <p className="mt-6 max-w-3xl font-serif text-xl leading-relaxed text-[#68736d]">{article.excerpt}</p>}<div className="mt-7 flex flex-wrap items-center gap-5 text-xs uppercase tracking-[0.12em] text-[#68736d]"><span className="flex items-center gap-2"><Calendar className="h-4 w-4 text-[#b36b3b]" /> {formatDate(article.published_at)}</span><span className="flex items-center gap-2"><Eye className="h-4 w-4 text-[#b36b3b]" /> {article.view_count || 0} views</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#2f5b48]" /> Editorial desk</span></div></div>
      {article.cover_image_url && <div className="mt-10 aspect-[16/7] overflow-hidden bg-[#d9d0c1]"><img src={article.cover_image_url} alt={article.title} className="h-full w-full object-cover" /></div>}
      <div className="grid gap-12 py-12 lg:grid-cols-[1fr_220px]"><article className="max-w-3xl"><div className="whitespace-pre-wrap font-serif text-lg leading-[1.9] text-[#293530]">{article.content}</div>{article.tags.length > 0 && <div className="mt-10 flex flex-wrap gap-2 border-t border-[#1e2926]/15 pt-5">{article.tags.map(tag => <span key={tag} className="border border-[#1e2926]/20 px-3 py-1 text-xs uppercase tracking-[0.1em] text-[#68736d]">#{tag}</span>)}</div>}</article><aside className="h-fit border-t border-[#1e2926]/20 pt-5 lg:border-l lg:border-t-0 lg:pl-6"><p className="flex items-center gap-2 font-serif text-xl font-bold"><Share2 className="h-4 w-4 text-[#b36b3b]" /> Share this story</p><div className="mt-4 grid gap-2"><Button variant="outline" size="sm" onClick={() => handleShare('copy')} className="justify-start rounded-none border-[#1e2926]/20">{copied ? 'Copied' : 'Copy link'}</Button><Button variant="outline" size="sm" onClick={() => handleShare('facebook')} className="justify-start rounded-none border-[#1e2926]/20"><Facebook className="mr-2 h-4 w-4" /> Facebook</Button><Button variant="outline" size="sm" onClick={() => handleShare('twitter')} className="justify-start rounded-none border-[#1e2926]/20"><Twitter className="mr-2 h-4 w-4" /> X / Twitter</Button><Button variant="outline" size="sm" onClick={() => handleShare('linkedin')} className="justify-start rounded-none border-[#1e2926]/20"><Linkedin className="mr-2 h-4 w-4" /> LinkedIn</Button></div><Link to="/opportunities" className="mt-8 block border-t border-[#1e2926]/20 pt-5 font-serif text-lg font-bold hover:text-[#b36b3b]">Looking for opportunities? <span className="text-[#b36b3b]">Visit the Desk →</span></Link></aside></div>{user?.role === 'admin' && <Button asChild variant="outline"><Link to={`/admin/news/${article.id}/edit`}>Edit article</Link></Button>}</div></main></>;
}
